{% set name = "plaster" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8351c7c7efdf33084c1de88dd0f422cbe7342534537b553c49b857b12d98c8c3

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - plaster

about:
  home: https://docs.pylonsproject.org/projects/plaster/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A loader interface around multiple config file formats.
  dev_url: https://github.com/Pylons/plaster

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
