{% set name = "plaster" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 136c09ecbd2a8eab1544fb8513cbd77a32f6e7052b1034fe53856bf74a172faa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - plaster

about:
  home: https://docs.pylonsproject.org/projects/plaster/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A loader interface around multiple config file formats.
  dev_url: https://github.com/Pylons/plaster

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
