travis:
  secure:
    BINSTAR_TOKEN: X85SpyPsGF1PdcDv+Il/ZoyLC1EMqjUNO0idcPgZ/VUnJpdR51+jZ3hk2Ry5axzFCTFRXN6nKeJwWqx9LmeA875nf4IMhlytleXgyPxzQWGvbRP3OtiCpHjF4K8c+TOmk1ehwaWdcbhCpJLpKA8LYYQKblyhMnbp9/LWm1MDSYX2z1Rx2/kugM9NJ41waAXs45uw5J0i48VyficJK/XUjuoTekJwPM0PiXoz8D70KxI4xqtEbJpuxCnnOVW/VItI67moofNjYAFItKIjdAlZctnzwcAYIsXUUqzDsnYjY/V85liCbP1c+/twH8PnFwyPiP+wPWCDv88WmHOzHDyTW2K6wy+CFObIZKRNfe5AyAoq1CnWp8SWGwsOrACvJ49jfGAfRwfcp9RWm1kfMvCWsjAj3t8BW+M/2BFXTK7UNdDC2foKYQsOFr80W3q+jmo1DZmVZtDkRTCh68gtC0JJgeS53gkwBJnD2MHZ8ML9p9PNwUAJB3Ujsy7/FERhWjC5Np12g+sYambOa6/O7kNWWnQscrQ3PY1lA4skq7JFNbMgMMAMpaUxwFGmaeojjwK7LuVb6DhI4u1t9TBTIgWL6WizrLGoQPwYQcjBjmQ1VZvOgHss8R0hG25lmxDNpV8fFJEUWtRcMV0UjH3Qzd0dC6uH5b7dcMJwyQtCUwvQDpk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
